#!/usr/bin/python

import os
import subprocess as sp
from PIL import Image

import sys

CAM="10.0.1.101"
if (sys.argv[0].endswith("-large")):
    STREAM="videoMain"
    width=320*3
    height=180*3
else:
    STREAM="videoSub"
    width=320
    height=180


pid = os.getpid()
realFilename=str(pid)+'.tiff'
tmpFilename='X'+realFilename
dir='/tmp/LIVE/'
realFilename=dir+realFilename
tmpFilename=dir+tmpFilename


USER="user"
PW="SECRETx1"


STREAM="rtsp://"+USER+":"+PW+"@"+CAM+"/"+STREAM
SIZE=str(width)+"x"+str(height)
command = [ "avconv",
            '-i', STREAM,
            '-loglevel', "error",
            '-f', 'image2pipe',
            '-pix_fmt', 'rgb24',
            '-s', SIZE,
            '-r', "10",
            '-vcodec', 'rawvideo', '-']
pipe = sp.Popen(command, stdout = sp.PIPE, bufsize=10**8)

import numpy
while 1:
    raw_image = pipe.stdout.read(width*height*3)
    imageA =  numpy.fromstring(raw_image, dtype='uint8')
    imageA = imageA.reshape((height,width,3))
    # throw away the data in the pipe's buffer.
    img = Image.fromarray(imageA)
    img.save(tmpFilename)
    os.rename(tmpFilename, realFilename);


pipe.stdout.flush()
